#热部署生效
#spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

# 数据源
spring:
#  autoconfigure:
#    #禁用Spring boot自身的自动配置类
#    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # 热部署生效
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  # 数据源
  datasource:
    name: mysql_test
#    jdbc-url: jdbc:mysql://aliyun:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 644886
    #driver-class-name: com.mysql.jdbc.Driver 自动加载
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      #driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      jdbc-url: jdbc:mysql://aliyun:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 644886
      default-auto-commit: false
      default-transaction-isolation: 4 # 2:读已提交 4：可重复读
      #配置初始化大小/最小/最大
      initial-size: 2
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  servlet:
    #文件上传
    multipart:
      #是否启用Spring MVC 多分部上传功能
      enabled: true
      #将文件写入磁盘的阀值。值可以使用后缀“ MB ”或“ KB ” 来表示兆字节或字节大小
      file-size-threshold: 0
      #location: D:/tmp
      max-file-size: 5MB
      max-request-size: 20MB
      #是否延迟多部件文件请求的参数和文件的解析
      resolve-lazily: false

  #自定义用户名和l密码
  security:
    user:
      name: pier
      password: 644886

  redis:
    # Redis服务器地址
    host: aliyun
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    #  自己redis设置的密码
    password: 644886
#    jedis:
#      pool:
#        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        #        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        max-wait: 2000
    #连接超时时间（毫秒）
    timeout: 10000

  rabbitmq:
    host: aliyun
    port: 5672
    username: pier
    password: 644886
    virtual-host: /
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true #消费者端的重试
      simple:
        acknowledge-mode: manual         # 开启ACK
        retry:
          enabled: true #消费者端的重试
        concurrency: 10  #消费者的最小数量
#        max-concurrency: 20  #消费者的最大数量
#        prefetch: 5  #在单个请求中处理的消息个数，他应该大于等于事务数量
        auto-startup: true  #启动时自动启动容器	true
        default-requeue-rejected: true  #投递失败时是否重新排队
    template:
      reply-timeout: 10000 #超时时间
      retry:
        enabled: true  #设置为true的时候RabbitTemplate(生产端)能够实现重试
#        initial-interval: 1000  #第一次与第二次发布消息的时间间隔 1000
        max-attempts: 3 #尝试发布消息的最大数量 3
#        max-interval: 10000  #尝试发布消息的最大时间间隔 10000
#        multiplier: 1.0  #上一次尝试时间间隔的乘数 1.0

  kafka:
    bootstrap-servers: aliyun:9092
    consumer:
      group-id: mygroup

  mail:
    username: 501311328@qq.com
    # 非密码而是授权码
    password: ktvrgsikqadbbhcb
    host: smtp.qq.com
    default-encoding: UTF-8
    smtp:
      ssl:
        enable: true

  #mongodb配置
  data:
    mongodb:
      uri: mongodb://pier1:644886@localhost:27017/test
#      host: localhost
#      username: pier1
#      password: 644886
#      port: 27017
#      database: test

# mybatis配置
mybatis:
#  config-location:
#    classpath:
#      mybatis-config:
#        xml: mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pier.bean

elasticsearch:
  # 一定要与服务器相同
  cluster-name: elasticsearch
  host: aliyun
  port: 9300
  http-port: 9200
  pool: 5

logging:
  config: classpath:logback.xml
#  level: error

app:
  java:
    # 读取maven的配置
    version: @java.version@

# 用于websocket
rabbitmq:
  queue:
    msg: spring-boot-queue-msg
    user: spring-boot-queue-user