#热部署生效
#spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

# 数据源
spring:
#  autoconfigure:
#    #禁用Spring boot自身的自动配置类
#    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # 热部署生效
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  # 数据源
  datasource:
    name: mysql_test
#    jdbc-url: jdbc:mysql://aliyun:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 644886
    #driver-class-name: com.mysql.jdbc.Driver 自动加载
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      #driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      jdbc-url: jdbc:mysql://aliyun:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 644886
      #配置初始化大小/最小/最大
      initial-size: 10
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    # Redis服务器地址
    host: aliyun
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    #  自己redis设置的密码
    password: 644886
#    jedis:
#      pool:
#        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        #        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 10000


# mybatis配置
mybatis:
#  config-location:
#    classpath:
#      mybatis-config:
#        xml: mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pier.bean

elasticsearch:
  # 一定要与服务器相同
  cluster-name: elasticsearch
  host: aliyun
  port: 9300
  pool: 5

logging:
  config: classpath:logback.xml
#  level: error